language: python
sudo: false
python:
- '2.6'
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install python-coveralls tox tox-travis
script: tox --recreate
after_success:
- pip install -e .
- py.test --cov=envoy_webhook_auth_decorator --cov-report=term-missing tests
- coveralls
deploy:
  provider: pypi
  user: sunzhongmou
  password:
    secure: d2F5ZGUxOTEK
  on:
    python: 2.7
